# Generated by Django 4.2.3 on 2023-07-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='mem',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
