# Generated by Django 4.2.3 on 2023-07-24 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pic_app', '0002_mem_comments_mem_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/posts', verbose_name='Изображение')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('is_ban', models.BooleanField(default=False, verbose_name='Отключено ли отображение')),
                ('author', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-date_time', 'title'),
            },
        ),
        migrations.CreateModel(
            name='NewsRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pic_app.news')),
            ],
            options={
                'verbose_name': 'Рейтинг к новости',
                'verbose_name_plural': 'Рейтинги к новостям',
                'ordering': ('-post', 'author'),
            },
        ),
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Текст комментария')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('author', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('news', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='pic_app.news', verbose_name='К какой новости')),
            ],
            options={
                'verbose_name': 'Комментарий к новости',
                'verbose_name_plural': 'Комментарии к новостям',
                'ordering': ('-date_time', 'news'),
            },
        ),
    ]
